model:
  name: "meta-llama/Llama-3.2-11B-Vision-Instruct"
  max_length: 512
  vision_config:
    image_size: 224
    patch_size: 16

training:
  batch_size: 8
  learning_rate: 2e-5
  num_epochs: 10
  gradient_accumulation_steps: 4
  warmup_steps: 100
  mixed_precision: "bf16"
  gradient_checkpointing: true

data:
  train_test_split: 0.2
  validation_split: 0.1
  seed: 42
  augmentation:
    enable: true
    horizontal_flip: true
    vertical_flip: false
    rotation_range: 15

output:
  checkpoint_dir: "outputs/checkpoints"
  log_dir: "outputs/logs"
